### ISSUE TITLE
images

### ISSUE THREAD

**Issue by nidayand** [nidayand/motor-on-roller-blind#1]
![screen shot 2017-10-04 at 14 33 04](https://user-images.githubusercontent.com/2181965/31178172-88dfe796-a918-11e7-89fe-cb6c2c98d838.png)
![screen shot 2017-10-04 at 14 32 48](https://user-images.githubusercontent.com/2181965/31178173-88feb7f2-a918-11e7-8b1a-4d5e39a9fe97.png)

**Comment by olskar** [comment]
Any news on the rework @nidayand? :)
